Vagrant::Config.run do |config|
  config.vm.box = "lucid32"

  #config.vm.define :provisioner do |subconf|
  #  # Sets up a puppet provisioning server for all other modules
  #  subconf.vm.network "34.34.34.10"
  #  subconf.vm.share_folder("manifests", "/etc/puppet/manifests", "conf/puppet/manifests")
  #  subconf.vm.share_folder("templates", "/etc/puppet/templates", "conf/puppet/templates")
  #  subconf.vm.share_folder("modules", "/etc/puppet/modules", "conf/puppet/modules")
  #  subconf.vm.share_folder("services", "/etc/puppet/services", "conf/puppet/services")
  #  subconf.vm.share_folder("plugins", "/etc/puppet/plugins", "conf/puppet/plugins")
  #  #subconf.vm.provision :puppet do |puppet|
  #  #  puppet.manifests_path = "conf/manifests"
  #  #  puppet.manifest_file = "provisioner.pp"
  #  #end
  #end
  #
  #config.vm.define :archiver do |subconf|
  #  subconf.vm.network "34.34.34.20"
  #  #config.vm.provision :puppet_server do |puppet|
  #  #  puppet.puppet_server = "34.34.34.10"
  #  #end
  #end



  #config.vm.forward_port "mongodb", 27017, 20000
  #config.vm.forward_port "mongodb-web-admin", 28017, 20001
  #config.vm.forward_port "archiver-rpc", 7080, 7080
  #config.vm.forward_port "archiver-thrift", 7081, 7081
  #config.vm.forward_port "archiver-ftp", 10000, 10000

  config.vm.share_folder("source", "/smac-source/smaclib", "smaclib")
  config.vm.share_folder("twisted-plugins", "/smac-source/twisted", "twisted")
  config.vm.share_folder("smac-modules", "/smac-source/modules", "modules")

  config.vm.define :archiver do |archiver|
    archiver.vm.network "34.34.34.10"

    archiver.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "conf/chef/cookbooks"
      chef.roles_path = "conf/chef/roles"

      chef.add_role "default"
      chef.add_role "archiver"

      chef.json.merge!({
          :mongodb => {:rest => true},
          :python => {
            :version => "2.6",
            :python => "python2.6",
          }
      })
    end
  end

  config.vm.define :analyzer do |analyzer|
    analyzer.vm.network "34.34.34.11"

    analyzer.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "conf/chef/cookbooks"
      chef.roles_path = "conf/chef/roles"

      chef.add_role "default"
      chef.add_role "analyzer"

      chef.json.merge!({
          :python => {
            :version => "2.6",
            :python => "python2.6",
          }
      })
    end
  end

end
