#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *
from ttypes import *

UNKNOWN_MIMETYPE = 7000
UNKNOWN_MIMETYPE_MSG = "Unknown mime type: {mimetype}"
INVALID_UPLOAD_ID = 7001
INVALID_UPLOAD_ID_MSG = "Invalid upload id: {upload_id}"
NO_SUITABLE_ENCODER = 7002
NO_SUITABLE_ENCODER_MSG = "No suitable encoder for {mimetype}"
INVALID_BITRATE = 7003
INVALID_BITRATE_MSG = "Invalid {media} bitrate: {bitrate}"
ASSET_NOT_FOUND = 7004
ASSET_NOT_FOUND_MSG = "Asset with ID '{asset_id}' not found"
TASK_NOT_FOUND = 7005
TASK_NOT_FOUND_MSG = "Task with ID '{task_id}' not found"
OPERATION_NOT_SUPPORTED = 7006
OPERATION_NOT_SUPPORTED_MSG = "Task '{task_id}' cannot be {action}"
INVALID_FORMAT = 7007
INVALID_FORMAT_MSG = "Invalid format '{mimetype}' for asset {asset_id}"
